icon: smallicon.png
logo: logo.png
logo_size: 320x240
menu_title: Fedora Remix Toolkit
menu_help: xdg-open FedoraRemixToolkit-Help.pdf &
num_columns: 3  # Define number of columns for the main menu

menu_items:

## Initial System Setup Tasks
  - name: Fedora Remix Basic Tasks
    column: 1  
    submenu_columns: 3 
    button_info: |
      This takes you to tasks for completing the basic setup of the Fedora Remix OS. It will update and configure root-level functions and OS and System-Level functions.
    items:
      - name: Update Packages (reboots)
        column: 1  # This submenu item will be in the first column
        command: sudo /opt/FedoraRemix/scripts/update_pkgs.sh
        button_info: |
          Update Fedora System Packages Using DNF and reboots when completed.
      - name: Create Root Password/Allow SSH
        column: 1  
        command: echo "Placeholder"
        button_info: |
          This will create a root password and allow SSH for the root user.
      - name: Create Root SSH Keys for Ansible
        column: 1  
        command: echo "Placeholder"
        button_info: |
          This will create a root SSH keys and setup the root user for Ansible.
      - name: Customize GNOME for root user
        column: 3  
        command: echo "Placeholder"
        button_info: |
          Customizes GNOME for the root user (enables extensions)
      - name: Customize Grub Bootloader
        column: 2
        command: echo "Placeholder"
        button_info: |
          This will customize the GRUB boot loader menu and style.
      - name: Install GNOME Extensions (reboots)
        column: 2
        command: echo "Placeholder"
        button_info: |
          This button installs GNOME extensions. It reboots when completed
      - name: Create PXE Boot Server
        column: 3
        command: echo "Placeholder"
        button_info: |
          This will setup PXE-Boot Services for Live booting Fedora Remix
      - name: Remove Tools from Auto-Start
        column: 3
        command: echo "Placeholder"
        button_info: |
          This will remove the Fedora Remix Tools from Autostart.

### User-Level Tasks

  - name: Perform User-Level Operations
    column: 2
    items:
      - name: Create User SSH Key and Prepare for Ansible
        command: echo "Placeholder"
        button_info: |
          Creates SSH key for current user and prepares system for Ansible use.
      - name: Update Sudoers file for User
        command: echo "Placeholder"
        button_info: |
          Updates Sudoers file for current user to not require a password.
      - name: Customize GNOME for User
        column: 2
        command: echo "Placeholder"
        button_info: |
          Customizes GNOME for current user.
      - name: Enable GNOME Extensions
        column: 2
        command: echo "Placeholder"
        button_info: |
          Enables GNOME Shell Extensions for current user.
      - name: Install VSCode Extensions
        column: 2
        command: echo "Placeholder"
        button_info: |
          Installs VSCode Extensions for the current user
      - name: Customize Ansible User Password
        column: 2
        command: echo "Placeholder"
        button_info: |
          Sets Ansible User Password

### System Maintenance and Repair Tasks
  - name: Maintenance and Tools Menu
    column: 3
    submenu_columns: 2
    button_info: |
      This menu has various utilities to 
    items:
      - name: Fix Python Kickstart
        column: 1
        command: echo "Placeholder"
        button_info: |
          This will fix an issue with PyKickstart and URL preventing livecd-creator from working.
      - name: Create Fingerprint Services
        column: 2
        command: echo "Placeholder"
        button_info: |
          This will enable the fingerprint services for users on selected Lenovo Thinkpads and Synaptic devices.